version: '3'
services:
  db:
    image: "postgres:11.12"
    environment: 
      - POSTGRES_PASSWORD=123
    ports:
      - "8001:5432"
    networks:
      default:
        aliases:
          - db
  server:
    build: . 
    ports:
      - "5000:5000"
    links:
      - db
    networks:
      - default